### ISSUE TITLE
API definitions with custom authentication methods cause a js error

### ISSUE THREAD

**Issue by triplepoint** [mulesoft/api-designer#213]
Attempting to create a RAML spec with a custom authentication method will cause an ungraceful javascript error when testing:

For the RAML file:
``` YAML
#%RAML 0.8
title: Demonstration API
baseUri: https://test.com/api
securitySchemes:
    - homeRolledAuth:
        description: a custom authentication header implementation
        type: x-custom-header-protocol
        describedBy:
          headers:
            X-Request-Token:
              type: string
/auth-ping:
    description: A demonstration ping service that requires authentication
    get:
        securedBy: [homeRolledAuth]
```
Attempting to:
- Click on "GET" for the /auth-ping endpoint
- select  the "HomeRolledAuth" authentication option
- click "GET"

will result in the following javascript error:
```
TypeError: Cannot read property 'authenticate' of undefined
    at TryIt.execute (http://designer.apihub.com/scripts/vendor.js:65786:17)
    at http://designer.apihub.com/scripts/vendor.js:18597:21
    at http://designer.apihub.com/scripts/vendor.js:26785:17
    at Scope.$eval (http://designer.apihub.com/scripts/vendor.js:20459:28)
    at Scope.$apply (http://designer.apihub.com/scripts/vendor.js:20557:23)
    at HTMLButtonElement.<anonymous> (http://designer.apihub.com/scripts/vendor.js:26784:21)
    at HTMLButtonElement.f.event.dispatch (http://api-portal.anypoint.mulesoft.com/sites/api-portal.anypoint.mulesoft.com/files/js/js_0gj6QcpfRH2jzTbCQqf7kEkm4MXY0UA_sRhwPc8jC1o.js:3:4351)
    at HTMLButtonElement.h.handle.i (http://api-portal.anypoint.mulesoft.com/sites/api-portal.anypoint.mulesoft.com/files/js/js_0gj6QcpfRH2jzTbCQqf7kEkm4MXY0UA_sRhwPc8jC1o.js:3:335) vendor.js:17840
```

Obviously this feature can't be made to work entirely, since the custom authentication protocol is unknown to the application, but a more robust error state would be better.
