### ISSUE TITLE
formParameters: !include employee_upsert_schema.map causes error in RAML

### ISSUE THREAD

**Issue by brettkroeder** [mulesoft/api-designer#227]
I'm trying to use an include for formParameters like I do for the json schema.  Since it wants a map I my include is:
       formParameters: !include employee_upsert_schema.map

The file looks like this:
```yaml
         first_name:
           description: Employee First Name
           type: string
           minLength: 2
           maxLength: 20
           required: true
           example: Joe
         last_name:
           description: Employee Last Name
           type: string
           minLength: 2
           maxLength: 20
           required: true
           example: Smith
```

But API Designer is telling me 'formalParameters' must be a map.
