### ISSUE TITLE
Getting and passing Authorisation Token into a header

### ISSUE THREAD

**Issue by carlskii** [mulesoft/api-designer#246]
Hi,

My API requires that I first get an auth token by calling an auth method within the API. This returns a token e.g. `1035837f-f452-c474-71d5-ee6b95bf1075`. This token needs to be added to a header for all subsequent API calls. e.g. 

```yaml
headers: 
        Authorization: 
                    description: |
                       Used to pass the authentication token to API.
                    type: string
                    required: true
                    example: API 1035837f-f452-c474-71d5-ee6b95bf1075
```

I've read through the RAML spec, but its not obvious to me if this can be achieved.
