### ISSUE TITLE
version 1.0 specifying unknown facet:formParameters? 

### ISSUE THREAD

**Issue by spidiTsakirales** [mulesoft/api-designer#400]
I have just started using raml version 1.0 .

I cannot find anything on the documentation which states formParameters are no longer supported. 
However the following is supported on version 0.8 but not on version 1.0 ?

```yaml
body:
  application/x-www-form-urlencoded:
    formParameters:
      value:
        displayName: value
        description: a description here
        required: true
        type: string
``` 

i get an error : specifying unknown facet:formParameters?

**Comment by Gregroam** [comment]
Use properties instead

**Comment by sichvoge** [comment]
What @Gregroam. you should use `properties` as described [here](https://github.com/raml-org/raml-spec/wiki/Breaking-Changes#defining-form-parameters-has-been-removed-in-favour-for-raml-types).

So your example should be

```yaml
body:
  application/x-www-form-urlencoded:
    formParameters:
      properties:
        displayName: value
        description: a description here
        required: true
        type: string
```
