### ISSUE TITLE
No errors in typed fragments

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#430]
Branch: develop
Milestone: v1
Related to: #410 

I don't see any errors in the following RAML typed fragment:

```yaml
#%RAML 1.0 Library

types:
  Dog:
    properties: 
      bark: boolean
      
annotationTypes: 
  deprecated: Dog
```

Please review all type fragments for errors and warnings.
