### ISSUE TITLE
Saving and modifying takes a long time.

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#431]
Branch: develop
Milestone: v1

Lets assume you have the following RAML:

```yaml
#%RAML 0.8
title: Ready

/example:
  get:
    responses: 
      200:
        body: 
          application/json:
```

Now change the RAML version from 0.8 to 1.0 and press CMD + S to save the file. The cursor is stuck from about 7s before the notification pops up that the file is saved.

The issue does not occur with the current master version.

**Comment by sichvoge** [comment]
The time to move the cursor actually takes also very long using the following typed fragment:

```yaml
#%RAML 1.0 Library

types:
  Dog:
    properties: 
      bark: boolean
      
annotationTypes: 
  deprecated: Dog
```

What I have done is:

1. set cursor behind `deprecated: Dog`
2. press the return key on your keyboard and delete `Dog`; you should already see that it will take seconds
3. try to write Dog again; same duration before something gets done

This is critical since its unusable right now even for very small RAML files. We should test performance with huge projects like the [Github API](https://github.com/raml-apis/GitHub) to evaluate problems.
