### ISSUE TITLE
Mock Service not accepting multiple occurrences of arrays 

### ISSUE THREAD

**Issue by faizzahmed** [mulesoft/api-designer#490]
My data def. is : 

```
mediaType: application/json
types:
  Insurances:
    type: object
    properties: 
      Insurance:
        type: object 
        properties:
          Coverage: 
            type: array
            items:
              properties:
                CoverageId: number
                CoverName: string
```
and the example used in mocking service for POST is 

```
          {
            "Insurance":{
                  "Coverage": [
                    {"CoverageId":     1554,
                    "CoverName":      "liability"},
                   {"CoverageId":     12132,
                    "CoverName":      "disease"}
                  ] 
            }
          }
```

the mocking service and documentation is generated but when i use try now option it fails with the error : 

```
{
  "error": "body: Insurance: Coverage: cannot be repeated"
}
```
When i add only 1 occurrence in the example post body it works fine , can someone suggest what is wrong ?
