### ISSUE TITLE
Array types not being displayed correctly

### ISSUE THREAD

**Issue by nallen01** [mulesoft/api-designer#497]
API Designer Version: 0.4.2 / 0.4.3
Browser: Chrome/59.0.3071.115 (64-bit)
OS: Windows 7 Enterprise SP1

Minimal example:
```
#%RAML 1.0
title: Example
types:
  People:
    type: array
    items:
      type: Person
  Person:
    properties:
     name:
        type: string
```

In the above case the GUI on API Designer shows `People` as being of time `items[]`, whereas it should be `Person[]`. Changing `People` to be explicitly of type `Person[]`, or using the shorthand for `items` (e.g. `items: Person`) works properly, but having an expanded type declaration as above does not.

Of note is that exporting OAS2 from the develop (0.4.3) branch exports a spec that correctly associates the `items` with `Person`. Re-importing this spec creates a RAML 1.0 spec in the format above with the same issues. Therefore this must be an issue with the GUI, not the RAML 1.0 parser.
